DROP DATABASE IF EXISTS M4_GAME;

CREATE DATABASE M4_GAME;

USE M4_GAME;



CREATE TABLE PLAYER(USERNAME VARCHAR(20) NOT NULL, PASSWORD VARCHAR(20), PRIMARY KEY (USERNAME));



CREATE TABLE MATCHES(ID INT NOT NULL, TIME TEXT, DURATION FLOAT, WINNER VARCHAR(20), PRIMARY KEY(ID));



CREATE TABLE GAME(ID_P VARCHAR(20), ID_M INT, FOREIGN KEY(ID_P) REFERENCES PLAYER(USERNAME), FOREIGN KEY(ID_M) REFERENCES MATCHES(ID));



-- Insertar dos jugadores

INSERT INTO PLAYER (USERNAME, PASSWORD) VALUES ('guilly19', '1234');

INSERT INTO PLAYER (USERNAME, PASSWORD) VALUES ('pogua', '1234');

